name: Demo Key Vault Secrets

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  get-secrets:
    name: Get Secrets from Azure Key Vault
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Gets the secrets from Key Vault and will show the result in the Actions log
      # The secret2 value will be masked in the logs
      # Masking is a good practice to prevent it from showing up when used in additional steps
      - name: Get Secrets
        id: secrets
        env:
          KEY_VAULT_NAME: ${{ secrets.AZURE_KEY_VAULT_NAME }}
        run: |
          SECRET1=$(az keyvault secret show --name "secret1" --vault-name "$KEY_VAULT_NAME" --query value -o tsv)
          SECRET2=$(az keyvault secret show --name "secret2" --vault-name "$KEY_VAULT_NAME" --query value -o tsv)
          echo "::add-mask::$SECRET2"
          echo "secret1=$SECRET1" >> "$GITHUB_OUTPUT"
          echo "secret2=$SECRET2" >> "$GITHUB_OUTPUT"

      # Shows using the outputs from the previous steps
      - name: Show Secrets
        run: |
          echo "secret1: ${{ steps.secrets.outputs.secret1 }}"
          echo "secret2: ${{ steps.secrets.outputs.secret2 }}"
