# This is a basic workflow to help you get started with Actions

name: Demo Key Vault Secrets

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  get-secrets:
    name: Get Secrets from Azure Key Vault
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Gets 'secret1' and will show the result in the Actions log
      - name: Get Secret1
        id: secret1
        env:
          KEY_VAULT_NAME: ${{ secrets.AZURE_KEY_VAULT_NAME }}
        run: |
          SECRET1=$(az keyvault secret show --name "secret1" --vault-name "$KEY_VAULT_NAME" --query value -o tsv)
          echo "secret=$SECRET1" >> "$GITHUB_OUTPUT"
          echo "Secret1: $SECRET1"

      # Gets 'secret2' and will mask the result in the Actions log
      # Masking is a good practice to prevent it from showing up when used in additional steps
      - name: Get Secret2
        id: secret2
        env:
          KEY_VAULT_NAME: ${{ secrets.AZURE_KEY_VAULT_NAME }}
        run: |
          SECRET2=$(az keyvault secret show --name "secret2" --vault-name "$KEY_VAULT_NAME" --query value -o tsv)
          echo "::add-mask::$SECRET2"
          echo "secret=$SECRET2" >> "$GITHUB_OUTPUT"
          echo "Secret2: $SECRET2"

      # Shows using the outputs from the previous steps
      - name: Show Secrets
        run: |
          echo "Secret1: ${{ steps.secret1.outputs.secret }}"
          echo "Secret2: ${{ steps.secret2.outputs.secret }}"
